annotations:
  category: DeveloperTools
  images: |
    - name: aspnet-core
      image: docker.io/bitnami/aspnet-core:8.0.6-debian-12-r0
    - name: dotnet-sdk
      image: docker.io/bitnami/dotnet-sdk:8.0.301-debian-12-r0
    - name: git
      image: docker.io/bitnami/git:2.45.2-debian-12-r0
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.0.6
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: ASP.NET Core is an open-source framework for web application development
  created by Microsoft. It runs on both the full .NET Framework, on Windows, and the
  cross-platform .NET Core.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/aspnet-core/img/aspnet-core-stack-220x234.png
keywords:
- asp.net
- dotnet
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: aspnet-core
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/aspnet-core
version: 6.2.1
